[googledrive]
type = drive
scope = drive.appfolder
token = {"access_token":"ya29.a0AcM612zhDXRnYbk0iK7g5_kchIUmZW7oqQ4EThSnR1Jz3KrdkKhO38Q5KXNDzJsMsDxQpG3tgzVaJPN8URHSYLFaV4G3miFyA-WqiyHMmaTuwCVBtKjG4LtYsTZxtAfWV_Ci7UXQhIS1AilGsnrC1bd0WJQX3sWMTlIg3oV_3gaCgYKAa8SARASFQHGX2MijTx0cHnyMwZGSZme57qt2A0177","token_type":"Bearer","refresh_token":"1//0eqbZaqzWFQnICgYIARAAGA4SNwF-L9Ir5HAgM6z5HcVwc82VKuncWbJJs-2AoeuFRdgaorYB3qUKaIkeZvAkwcrz8vGOkK1iljQ","expiry":"2024-09-02T07:30:00.800973507+07:00"}
team_drive = 
root_folder_id = appDataFolder

